export const END_COMPLETION = '[DONE]';
export const ENV = {
  PINECONE_API_KEY: 'PINECONE_API_KEY',
  PINECONE_ENVIRONMENT: 'PINECONE_ENVIRONMENT',
  PINECONE_INDEX: 'PINECONE_INDEX',
  OPEN_AI_API_KEY: 'OPEN_AI_API_KEY',
  NEXT_PUBLIC_BACKEND_API: 'NEXT_PUBLIC_BACKEND_API',
};

export const DOC_EMBEDDING_MODEL = 'text-search-babbage-doc-001';
export const QUERY_EMBEDDING_MODEL = 'text-search-babbage-query-001';

export const EMBEDDING_MODEL_DIMENSIONS = 2048;
