name: Build & Push frontend image to Dockerhub and deploy on Elastic Beanstalk
on:
  push:
    branches:
      - remodel
    paths:
      - 'packages/frontend/**'
      - 'packages/shared/**'
      - 'packages/backend/prisma/**'
      - 'package.json'
      - 'frontend.Dockerfile'
      - 'Dockerrun.aws.json'
      - '.github/workflows/deploy-frontend.yml'
      - 'package.json'
      - 'package-lock.json'
jobs:
  build_docker_images:
    name: Set up Environment Variables & Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Create .env files
        run: |
          echo "NODE_ENV=production" >> ./packages/frontend/.env.local
          echo "NEXT_PUBLIC_BACKEND_API=${{ secrets.NEXT_PUBLIC_BACKEND_API }}" >> ./packages/frontend/.env.local

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
          logout: true
      - name: Build Docker Frontend Image
        run: docker build -t ${{ secrets.DOCKERHUB_FRONTEND_REPO }} -f
          ./frontend.Dockerfile .
      - name: Tag Our Frontend Image
        run: docker tag ${{ secrets.DOCKERHUB_FRONTEND_REPO }}
          ${{ secrets.DOCKERHUB_FRONTEND_REPO }}:${{ github.sha }}
      - name: Push Frontend to DockerHub
        run: docker push ${{ secrets.DOCKERHUB_FRONTEND_REPO }}:${{ github.sha }}
      - name: Prepare Beanstalk Deployment Package
        run: |
          echo 'Replacing TAG in Dockerrun.aws.json...'
          sed -i -e "s|<DOCKERHUB_REPO>|$DOCKERHUB_REPO|g" Dockerrun.aws.json
          sed -i -e "s|<TAG>|$SHA|g" Dockerrun.aws.json
          sed -i -e "s|<CONTAINER_PORT>|$CONTAINER_PORT|g" Dockerrun.aws.json
          sed -i -e "s|<HOST_PORT>|$HOST_PORT|g" Dockerrun.aws.json
          echo 'Creating deployment package...'
          zip -r deploy-frontend.zip Dockerrun.aws.json
        env:
          SHA: ${{ github.sha }}
          CONTAINER_PORT: 3000
          HOST_PORT: 3000
          DOCKERHUB_REPO: ${{ secrets.DOCKERHUB_FRONTEND_REPO }}
      - name: Get Timestamp
        shell: bash
        run: echo "##[set-output name=timestamp;]$(date '+%Y%m%d%H%M%S')"
        id: get_timestamp
      - name: Get Elastic Beanstalk Label
        shell: bash
        run: echo "##[set-output name=label;]$(echo ${NAME}-${TIMESTAMP})"
        id: get_frontend_label
        env:
          TIMESTAMP: ${{ steps.get_timestamp.outputs.timestamp }}
          NAME: ${{ secrets.AWS_EB_FRONTEND_ENVIRONMENT }}
      - name: Deploy Frontend to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.AWS_EB_APPLICATION_NAME }}
          environment_name: ${{ secrets.AWS_EB_FRONTEND_ENVIRONMENT }}
          version_label: ${{ steps.get_frontend_label.outputs.label }}
          region: eu-west-3
          deployment_package: deploy-frontend.zip
