name: Push images to Dockerhub and deploy on Elastic Beanstalk
on:
  push:
    branches:
      - master
jobs:
  build_docker_images:
    name: build docker images
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
          logout: true
      - name: Build Server image
        run: docker build -t abdoumell/papegaai -f
          ./Dockerfile .
      - name: Tag our Image
        run: docker tag abdoumell/papegaai
          abdoumell/papegaai:latest
      - name: Push to dockerhub
        run: docker push abdoumell/papegaai
      - name: Prepare Beanstalk Deployment Package
        run: |
          echo 'Creating deployment package...'
          zip -r deploy.zip Dockerfile Dockerrun.aws.json .ebextensions
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: papegaai
          environment_name: Papegaai-web-app
          version_label: ${{ github.sha }}
          region: eu-west-3
          deployment_package: deploy.zip
